DROP TABLE IF EXISTS fairs_users CASCADE; 

CREATE TABLE fairs_users (
  id SERIAL PRIMARY KEY,
  fair_id INTEGER REFERENCES fairs(id) ON DELETE CASCADE,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE
);