INSERT INTO users (
  first_name,
  last_name,
  email,
  password,
  username,
  profile_picture,
  bio,
  resume) 
VALUES
('Louisa', 'Meyer', 'louisa@hotmail.com', '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.', 'louisa', 'https://images.unsplash.com/photo-1607746882042-944635dfe10e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2340&q=80', 'Health goth seitan bicycle rights gastropub deserunt. Gentrify tacos blue bottle letterpress before they sold out deserunt narwhal synth paleo sunt wayfarers excepteur. Trust fund meggings air plant ennui, deep v raw denim PBR&B blue bottle. Ullamco laborum in fugiat. Vaporware occupy four loko, slow-carb dolor chia succulents. Four dollar toast ethical glossier, vinyl letterpress hammock in. Culpa heirloom chicharrones ut enim exercitation, authentic YOLO est.', ''),
('Dominic', 'Parks', 'dominic@outlook.com', '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.', 'dominic', 'https://images.unsplash.com/photo-1601455763557-db1bea8a9a5a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2412&q=80', 'Food truck in adipisicing, woke kombucha copper mug flexitarian edison bulb try-hard. Brooklyn taxidermy pinterest health goth you probably heard of them. Bespoke la croix fixie deserunt hexagon, williamsburg next level keytar aute health goth. Skateboard banh mi non ea blog. Mustache four dollar toast ut thundercats, art party pinterest scenester next level fugiat flexitarian messenger bag wolf 8-bit et.', ''),
('Sue', 'Luna', 'sue@gmx.com', '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.', 'sue', 'https://images.unsplash.com/photo-1544725176-7c40e5a71c5e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2334&q=80', 'Bespoke scenester drinking vinegar pariatur officia mustache ullamco, etsy vaporware YOLO four loko brunch raclette skateboard. Readymade anim artisan pabst voluptate pop-up VHS aliquip nostrud eu blue bottle dreamcatcher hella post-ironic banh mi. +1 meggings YOLO in iPhone live-edge. Meggings gluten-free asymmetrical laboris do authentic cillum master cleanse, mustache raclette wayfarers.', ''),
('Rosalie', 'Garza', 'rosalie@gmx.com', '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.', 'rosalie', 'https://images.unsplash.com/photo-1628890923662-2cb23c2e0cfe?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2340&q=80', 'Lo-fi shoreditch sriracha, sint semiotics voluptate crucifix authentic mixtape elit anim aute. Man braid plaid artisan lomo, hoodie vaporware exercitation authentic. Sriracha tbh umami eiusmod. Godard ullamco cupidatat, disrupt celiac neutra DIY locavore butcher taxidermy ipsum tbh. PBR&B unicorn migas vice XOXO meh. Banjo kogi franzen, man braid austin aliquip cornhole twee.', ''),
('Etta', 'West', 'etta@yahoo.com', '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.', 'etta', 'https://api.multiavatar.com/4e757862adb3186abb.png', 'Cred brunch tempor cillum incididunt tofu cronut consequat umami aesthetic ut. Pour-over 3 wolf moon skateboard affogato hammock jean shorts heirloom dreamcatcher incididunt meh. Typewriter exercitation waistcoat portland, prism subway tile vegan jean shorts banjo raw denim XOXO dolore retro. Sed do fingerstache health goth, before they sold out scenester mlkshk cillum lomo laboris. In vaporware glossier, intelligentsia neutra fixie nisi. Cillum sint shoreditch eiusmod, la croix lyft bicycle rights aliquip aesthetic art party palo santo etsy nostrud adipisicing.', ''),
('Eva', 'Stanley', 'eva@ymail.com', '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.', 'eva', 'https://images.unsplash.com/photo-1580489944761-15a19d654956?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=922&q=80', 'Shoreditch leggings taxidermy, normcore +1 literally fanny pack affogato. Brunch pop-up taiyaki kinfolk four loko XOXO photo booth migas post-ironic. Flexitarian vegan glossier, meggings pug gochujang shabby chic hashtag typewriter. Pug activated charcoal pitchfork iPhone.' ,''),
('Margaret', 'Wong', 'margaret@icloud.com', '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.', 'margaret', 'https://images.unsplash.com/photo-1568822617270-2c1579f8dfe2?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1160&q=80', 'Heirloom portland food truck ramps gochujang everyday carry vaporware wolf woke biodiesel. Hella aesthetic brooklyn, gochujang man braid small batch hoodie cold-pressed vaporware tumeric thundercats.' ,''),
('Leroy', 'Hart', 'leroy@inbox.com', '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.', 'leroy', 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1160&q=80', 'Mixtape banh mi gluten-free coloring book street art, brooklyn PBR&B slow-carb meh. Freegan ugh neutra franzen affogato. Small batch kombucha adaptogen migas helvetica, kickstarter disrupt pitchfork whatever.' ,'')
 ;
