INSERT INTO users (
  first_name,
  last_name,
  email,
  password,
  username,
  profile_picture,
  bio,
  resume) 
VALUES
 ('Louisa', 'Meyer', 'louisa@hotmail.com', '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.', 'louisa', 'https://api.multiavatar.com/Major%20Salt.png', 'Health goth seitan bicycle rights gastropub deserunt. Gentrify tacos blue bottle letterpress before they sold out deserunt narwhal synth paleo sunt wayfarers excepteur. Trust fund meggings air plant ennui, deep v raw denim PBR&B blue bottle. Ullamco laborum in fugiat. Vaporware occupy four loko, slow-carb dolor chia succulents. Four dollar toast ethical glossier, vinyl letterpress hammock in. Culpa heirloom chicharrones ut enim exercitation, authentic YOLO est.', ''),
('Dominic', 'Parks', 'dominic@outlook.com', '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.', 'dominic', 'https://api.multiavatar.com/80a89f600859ea69fc.png', 'Food truck in adipisicing, woke kombucha copper mug flexitarian edison bulb try-hard. Brooklyn taxidermy pinterest health goth you probably heard of them. Bespoke la croix fixie deserunt hexagon, williamsburg next level keytar aute health goth. Skateboard banh mi non ea blog. Mustache four dollar toast ut thundercats, art party pinterest scenester next level fugiat flexitarian messenger bag wolf 8-bit et.', ''),
('Sue', 'Luna', 'sue@gmx.com', '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.', 'sue', 'https://api.multiavatar.com/beae905e71a01ad277.png', 'Bespoke scenester drinking vinegar pariatur officia mustache ullamco, etsy vaporware YOLO four loko brunch raclette skateboard. Readymade anim artisan pabst voluptate pop-up VHS aliquip nostrud eu blue bottle dreamcatcher hella post-ironic banh mi. +1 meggings YOLO in iPhone live-edge. Meggings gluten-free asymmetrical laboris do authentic cillum master cleanse, mustache raclette wayfarers.', ''),
('Rosalie', 'Garza', 'rosalie@gmx.com', '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.', 'rosalie', 'https://api.multiavatar.com/75307b93a3e54cde63.png', 'Lo-fi shoreditch sriracha, sint semiotics voluptate crucifix authentic mixtape elit anim aute. Man braid plaid artisan lomo, hoodie vaporware exercitation authentic. Sriracha tbh umami eiusmod. Godard ullamco cupidatat, disrupt celiac neutra DIY locavore butcher taxidermy ipsum tbh. PBR&B unicorn migas vice XOXO meh. Banjo kogi franzen, man braid austin aliquip cornhole twee.', ''),
('Etta', 'West', 'etta@yahoo.com', '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.', 'etta', 'https://api.multiavatar.com/4e757862adb3186abb.png', 'Cred brunch tempor cillum incididunt tofu cronut consequat umami aesthetic ut. Pour-over 3 wolf moon skateboard affogato hammock jean shorts heirloom dreamcatcher incididunt meh. Typewriter exercitation waistcoat portland, prism subway tile vegan jean shorts banjo raw denim XOXO dolore retro. Sed do fingerstache health goth, before they sold out scenester mlkshk cillum lomo laboris. In vaporware glossier, intelligentsia neutra fixie nisi. Cillum sint shoreditch eiusmod, la croix lyft bicycle rights aliquip aesthetic art party palo santo etsy nostrud adipisicing.', '')
 ;
