INSERT INTO organizations (
  name,
  description,
  email,
  industry,
  website,
  logo
)
VALUES
('Newbold Ltd', 'Direct trade enamel pin letterpress craft beer scenester skateboard bitters plaid 3 wolf moon biodiesel meh migas iPhone squid keffiyeh. Lomo raw denim glossier slow-carb actually. Keytar ugh pitchfork bushwick XOXO pug intelligentsia tbh vape vexillologist art party lumbersexual microdosing schlitz. Shoreditch butcher schlitz post-ironic, cornhole godard franzen shaman pabst kinfolk biodiesel mixtape enamel pin hammock bushwick. Chicharrones tumblr plaid you probably havent heard of them microdosing stumptown cray keytar letterpress cold-pressed literally cardigan kale chips messenger bag. Poke gentrify marfa, hammock put a bird on it cloud bread coloring book yr mlkshk small batch truffaut.','newbold@mail.com','Environmental Services','https://mondrianandme.com/', 'https://pngimg.com/uploads/mcdonalds/mcdonalds_PNG23.png'),
('Earl Ltd', 'Direct trade cronut chartreuse biodiesel hexagon. Slow-carb air plant intelligentsia af hoodie fixie pok pok taxidermy mustache. Listicle affogato meggings hella woke shoreditch cred prism XOXO pitchfork quinoa messenger bag bespoke wolf. Poutine pork belly edison bulb, hot chicken cliche microdosing vinyl snackwave meh fashion axe. Ugh tattooed lyft, sriracha deep v affogato gochujang ethical retro squid seitan yuccie vexillologist vaporware.','earl@mail.com','Foodstuff & Beverage','http://corndog.io/','https://pngimg.com/uploads/kfc/kfc_PNG50.png'),
('Ennis Ltd', 'Taiyaki green juice freegan vinyl 3 wolf moon you probably havent heard of them, subway tile wayfarers retro pop-up bespoke schlitz. Enamel pin intelligentsia cray, messenger bag man braid retro mixtape pok pok dreamcatcher tumblr vinyl kogi fanny pack. 90s cornhole selvage butcher farm-to-table unicorn street art whatever chia coloring book. Cold-pressed forage VHS hell of vexillologist flexitarian banjo pitchfork actually 3 wolf moon post-ironic polaroid. Taiyaki chartreuse ugh gluten-free, direct trade narwhal cornhole street art palo santo authentic four loko cloud bread brunch vaporware. Stumptown vinyl master cleanse franzen knausgaard pork belly. Tumblr neutra locavore cloud bread.', 'ennis@mail.com', 'Health Care', 'https://checkboxrace.com/','https://pngimg.com/uploads/fifa/fifa_PNG29.png'),
('Coxon Ltd', 'Neutra twee heirloom polaroid poke af lyft williamsburg yuccie letterpress small batch actually. Crucifix literally swag iPhone, skateboard YOLO try-hard post-ironic shoreditch. You probably havent heard of them biodiesel unicorn synth prism mumblecore trust fund sartorial try-hard YOLO. Raw denim post-ironic meggings twee scenester microdosing tumblr iceland mixtape deep v small batch meditation viral. Adaptogen prism paleo vegan celiac franzen flannel authentic live-edge chillwave waistcoat bushwick austin listicle. Lyft four dollar toast celiac, XOXO fashion axe knausgaard salvia poutine edison bulb.', 'coxon@mail.com','Advertising Agency','https://alwaysjudgeabookbyitscover.com/','https://pngimg.com/uploads/gopro_logo/gopro_logo_PNG29.png'),
('Gilbert Ltd', 'Kitsch four dollar toast blue bottle hashtag hexagon hot chicken. Hell of glossier actually brunch pug kale chips. Skateboard single-origin coffee put a bird on it, forage polaroid chambray franzen gochujang artisan af stumptown twee. Taiyaki venmo green juice kombucha lumbersexual freegan roof party listicle hot chicken offal man bun whatever lyft. Selvage offal cronut coloring book lomo pour-over.', 'gilbert@mail.com','Wholesale & Retail','https://thatsthefinger.com/','https://pngimg.com/uploads/burger_king/burger_king_PNG16.png'),
('Edwards Ltd', 'Ramps PBR&B seitan paleo. Man braid literally readymade hexagon poke. Lumbersexual microdosing 3 wolf moon trust fund tofu poutine lyft sustainable DIY next level offal truffaut marfa synth. Ethical trust fund pinterest taiyaki, gentrify live-edge twee iPhone fashion axe XOXO 90s fanny pack. Intelligentsia bicycle rights sartorial, microdosing trust fund kitsch tumblr palo santo semiotics umami salvia actually. Gastropub tofu chambray kitsch paleo pitchfork. Iceland banh mi neutra street art, retro master cleanse schlitz.','edwards@mail.com','Convention & Exhibition Services','https://checkboxolympics.com/','https://pngimg.com/uploads/starbucks/starbucks_PNG18.png'),
('Pinter Ltd', 'Shoreditch paleo before they sold out chillwave normcore DIY succulents XOXO intelligentsia beard. Chartreuse fingerstache asymmetrical, photo booth aesthetic next level humblebrag kale chips. Roof party actually pinterest pug shoreditch synth farm-to-table godard semiotics everyday carry chambray. Williamsburg meditation squid air plant forage viral beard semiotics sriracha tumeric small batch. Gastropub ennui typewriter YOLO chia viral green juice distillery portland food truck street art ramps yr plaid tumeric.','pinter@mail.com','Logistics','https://cant-not-tweet-this.com/','https://pngimg.com/uploads/pokemon_logo/pokemon_logo_PNG9.png'),
('Lyons Ltd', 'Intelligentsia cronut XOXO slow-carb gochujang literally fanny pack sustainable adaptogen succulents tumeric tacos air plant. Irony selfies craft beer ennui tilde skateboard keytar shoreditch bushwick. Enamel pin try-hard coloring book disrupt meditation, mustache actually organic pop-up farm-to-table brooklyn paleo. Gluten-free jean shorts echo park craft beer bicycle rights distillery mumblecore intelligentsia prism salvia taxidermy. Farm-to-table echo park jianbing cliche single-origin coffee. Kitsch poke semiotics portland marfa air plant sustainable drinking vinegar farm-to-table fashion axe hoodie lumbersexual snackwave. Taxidermy air plant williamsburg put a bird on it tofu vegan deep v gochujang hot chicken YOLO selfies typewriter pop-up.','lyons@mail.com','Media','https://longdogechallenge.com/','https://pngimg.com/uploads/photoshop/photoshop_PNG42.png'),
('Rogan Ltd', 'Disrupt asymmetrical flannel lyft shabby chic shaman pug franzen paleo aesthetic chambray squid green juice. Twee 90s kickstarter pabst shabby chic live-edge polaroid. Microdosing snackwave synth, fingerstache cornhole biodiesel hashtag four loko kogi mixtape echo park aesthetic viral pitchfork. Jianbing asymmetrical knausgaard disrupt listicle thundercats retro bushwick direct trade tumblr vaporware lo-fi. Next level fanny pack air plant, pour-over poutine unicorn kitsch jianbing authentic chartreuse knausgaard. Affogato cray single-origin coffee tilde tofu blog.','rogan@mail.com','Entertainment / Art / Recreation','https://onesquareminesweeper.com/','https://pngimg.com/uploads/nike/nike_PNG19.png'),
('Keats Ltd', 'Copper mug heirloom fam organic kickstarter vape letterpress quinoa authentic aesthetic. Biodiesel occupy organic vinyl photo booth palo santo, try-hard pop-up chambray. Knausgaard iceland twee snackwave VHS literally whatever. Street art adaptogen tattooed, intelligentsia disrupt sustainable pickled.','keats@mail.com','Hotel & Hospitality','https://puginarug.com/','http://pngimg.com/uploads/adidas/adidas_PNG7.png'),
('Edwards Ltd', 'Swag chartreuse actually hashtag keffiyeh lumbersexual. Vape tote bag PBR&B austin gentrify, 8-bit post-ironic messenger bag twee chia wayfarers cray selvage. Four loko ugh dreamcatcher DIY. Bespoke narwhal subway tile franzen polaroid, sartorial hot chicken mixtape typewriter. Tousled hell of green juice poke sriracha, hoodie pop-up pitchfork cronut fixie biodiesel. 90s cornhole raw denim salvia, vexillologist street art sustainable austin man bun kombucha snackwave.','edwards@mail.com','Motor Vehicles','http://eelslap.com/','https://pngimg.com/uploads/olympic_rings/olympic_rings_PNG8.png'),
('Vardy Ltd', 'Lumbersexual viral seitan cloud bread master cleanse tumeric single-origin coffee you probably havent heard of them ramps edison bulb. Lo-fi small batch af poke VHS bushwick. Lyft food truck bicycle rights live-edge, brooklyn sriracha pop-up tattooed palo santo listicle narwhal salvia unicorn glossier selfies. Pitchfork next level ramps, brooklyn before they sold out salvia tilde flannel hashtag tofu helvetica farm-to-table yuccie art party. Slow-carb blue bottle vegan kinfolk.', 'vardy@mail.com', 'Banking / Finance / Securities / Investments', 'http://burymewithmymoney.com/','https://blog.hubspot.com/hubfs/image8-2.jpg')
;