INSERT INTO  fairs (
  name,
  host_id,
  description,
  start_time,
  end_time,
  poster
) 
VALUES
('Lindgren Shields and Champlin', 1, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo rhoncus sed vestibulum sit amet cursus id, turpis. Integer aliquet massa id lobortis convallis, tortor risus dapibus augue vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.', 'Fri, 14 Jan 2022 12:00:00 GMT', 'Fri, 14 Jan 2022 23:00:00 GMT', 'http://dummyimage.com/244x100.png/dddddd/000000'),
('Lindgren Shields and Champlin', 1, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo rhoncus sed vestibulum sit amet cursus id, turpis. Integer aliquet massa id lobortis convallis, tortor risus dapibus augue vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.', 'Fri, 21 Jan 2022 12:00:00 GMT', 'Fri, 21 Jan 2022 23:00:00 GMT', 'http://dummyimage.com/244x100.png/dddddd/000000'),
('Lindgren Shields and Champlin', 1, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo rhoncus sed vestibulum sit amet cursus id, turpis. Integer aliquet massa id lobortis convallis, tortor risus dapibus augue vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.', 'Fri, 21 Jan 2022 12:00:00 GMT', 'Fri, 21 Jan 2022 23:00:00 GMT', 'http://dummyimage.com/244x100.png/dddddd/000000'),
('Lindgren Shields and Champlin', 1, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo rhoncus sed vestibulum sit amet cursus id, turpis. Integer aliquet massa id lobortis convallis, tortor risus dapibus augue vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.', 'Fri, 21 Jan 2022 12:00:00 GMT', 'Fri, 21 Jan 2022 23:00:00 GMT', 'http://dummyimage.com/244x100.png/dddddd/000000'),
('Lindgren Shields and Champlin', 1, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo rhoncus sed vestibulum sit amet cursus id, turpis. Integer aliquet massa id lobortis convallis, tortor risus dapibus augue vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.', 'Fri, 21 Jan 2022 12:00:00 GMT', 'Fri, 21 Jan 2022 23:00:00 GMT', 'http://dummyimage.com/244x100.png/dddddd/000000'),
('Lindgren Shields and Champlin', 1, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo rhoncus sed vestibulum sit amet cursus id, turpis. Integer aliquet massa id lobortis convallis, tortor risus dapibus augue vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.', 'Fri, 21 Jan 2022 12:00:00 GMT', 'Fri, 21 Jan 2022 23:00:00 GMT', 'http://dummyimage.com/244x100.png/dddddd/000000'),
('Lindgren Shields and Champlin', 1, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo rhoncus sed vestibulum sit amet cursus id, turpis. Integer aliquet massa id lobortis convallis, tortor risus dapibus augue vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.', 'Fri, 21 Jan 2022 12:00:00 GMT', 'Fri, 21 Jan 2022 23:00:00 GMT', 'http://dummyimage.com/244x100.png/dddddd/000000'),
('Frami-Kuhn', 2, 'Donec dapibus.', 'Thu, 13 Jan 2022 12:00:00 GMT', 'Thu, 13 Jan 2022 12:00:00 GMT', 'http://dummyimage.com/249x100.png/ff4444/ffffff')
;