INSERT INTO jobs
  (
  title,
  created_at,
  description,
  location,
  organization_id,
  salary,
  experience
  )
VALUES
  ('Corporate Law Administrative Assistant', (current_timestamp - interval '300 hour'), 'Yuccie pug beard cronut, farm-to-table listicle narwhal wolf whatever tattooed mumblecore sartorial kogi sustainable pok pok. Artisan godard food truck kickstarter, microdosing sriracha bitters you probably havent heard of them. Portland brooklyn freegan, etsy quinoa celiac mustache asymmetrical tattooed wolf. Lyft you probably havent heard of them kombucha chillwave unicorn readymade, chambray cred.', 'Vernon, BC', 1, '$50,000', '3 years to less than 5 years'),
  ('Superintendent, Building ', (current_timestamp - interval '200 hour'), 'helvetica poke meh actually fashion axe whatever. Cold-pressed vexillologist kitsch tacos. Four dollar toast knausgaard helvetica vice iPhone williamsburg truffaut. Truffaut swag ramps scenester, crucifix post-ironic lumbersexual shoreditch food truck air plant tilde mumblecore wolf. Snackwave paleo drinking vinegar kinfolk kale chips listicle. Plaid cray franzen readymade, cold-pressed fingerstache iceland everyday carry banh mi shaman schlitz gluten-free gochujang photo booth. Single-origin coffee gochujang selvage hot chicken literally iceland.', 'Gatineau, QC', 1, 'Salary$$38,000 to $40,000', '1 year to less than 2 years'),
  ('Property Manager', (current_timestamp - interval '100 hour'), 'tofu chicharrones tumblr organic. Shaman +1 church-key sustainable microdosing, butcher 3 wolf moon polaroid asymmetrical snackwave banh mi neutra. Locavore coloring book mustache, chillwave semiotics beard wolf artisan pinterest skateboard everyday carry retro. XOXO vice venmo jean shorts normcore selvage. Tilde semiotics roof party, butcher woke before they sold out hella paleo everyday carry typewriter fanny pack', 'Truro Heights, NS', 1, '$32,000 to $42,000', 'No experience'),
  ('', (current_timestamp - interval '50 hour'), 'description', 'location', 1, 'salary', 'experience'),
  ('', (current_timestamp - interval '210 hour'), 'description', 'location', 2, 'salary', 'experience'),
  ('', (current_timestamp - interval '30 hour'), 'description', 'location', 2, 'salary', 'experience'),
  ('', (current_timestamp - interval '400 hour'), 'description', 'location', 3, 'salary', 'experience'),
  ('', (current_timestamp - interval '330 hour'), 'description', 'location', 3, 'salary', 'experience'),
  ('', (current_timestamp - interval '210 hour'), 'description', 'location', 3, 'salary', 'experience'),
  ('', (current_timestamp - interval '180 hour'), 'description', 'location', 3, 'salary', 'experience'),
  ('', (current_timestamp - interval '400 hour'), 'description', 'location', 4, 'salary', 'experience'),
  ('Technical Support Analyst - Systems', (current_timestamp - interval '140 hour'), 'Vape cred wolf banh mi try-hard edison bulb wayfarers freegan. You probably havent heard of them normcore mumblecore master cleanse coloring book. Quinoa cardigan ennui squid. Whatever shoreditch gentrify wolf shabby chic.', 'Saint John, NB', 4, '$35,000 to $38,500', '1 year to less than 2 years'),
  ('', (current_timestamp - interval '10 hour'), 'description', 'location', 4, 'salary', 'experience'),
  ('', (current_timestamp - interval '200 hour'), 'description', 'location', 5, 'salary', 'experience'),
  ('', (current_timestamp - interval '160 hour'), 'description', 'location', 5, 'salary', 'experience'),
  ('', (current_timestamp - interval '80 hour'), 'description', 'location', 5, 'salary', 'experience'),
  ('', (current_timestamp - interval '50 hour'), 'description', 'location', 5, 'salary', 'experience'),
  ('', (current_timestamp - interval '90 hour'), 'description', 'location', 6, 'salary', 'experience'),
  ('', (current_timestamp - interval '20 hour'), 'description', 'location', 6, 'salary', 'experience'),
  ('', (current_timestamp - interval '100 hour'), 'description', 'location', 7, 'salary', 'experience'),
  ('', (current_timestamp - interval '50 hour'), 'description', 'location', 7, 'salary', 'experience'),
  ('', (current_timestamp - interval '40 hour'), 'description', 'location', 7, 'salary', 'experience'),
  ('', (current_timestamp - interval '130 hour'), 'description', 'location', 8, 'salary', 'experience'),
  ('', (current_timestamp - interval '90 hour'), 'description', 'location', 8, 'salary', 'experience'),
  ('', (current_timestamp - interval '50 hour'), 'description', 'location', 8, 'salary', 'experience'),
  ('Pilot, Airline', (current_timestamp - interval '34 hour'), 'Organic try-hard squid gochujang keffiyeh. Schlitz selvage craft beer, you probably havent heard of them semiotics offal sustainable single-origin coffee chartreuse bushwick dreamcatcher viral. Selvage tilde man bun williamsburg waistcoat. Aesthetic PBR&B lo-fi mumblecore hell of. Lo-fi meh farm-to-table, messenger bag kinfolk etsy cronut woke vaporware wayfarers. Vinyl chartreuse asymmetrical, flexitarian 3 wolf moon microdosing keytar church-key street art pabst shaman.', 'La Ronge, SK', 8, '$70,440.6 to $84,279.48', '3 years to less than 5 years'),
  ('', (current_timestamp - interval '3 hour'), 'description', 'location', 8, 'salary', 'experience'),
  ('', (current_timestamp - interval '120 hour'), 'description', 'location', 9, 'salary', 'experience'),
  ('', (current_timestamp - interval '84 hour'), 'description', 'location', 9, 'salary', 'experience'),
  ('', (current_timestamp - interval '200 hour'), 'description', 'location', 10, 'salary', 'experience'),
  ('', (current_timestamp - interval '150 hour'), 'description', 'location', 10, 'salary', 'experience'),
  ('', (current_timestamp - interval '20 hour'), 'description', 'location', 10, 'salary', 'experience'),
  ('', (current_timestamp - interval '310 hour'), 'description', 'location', 11, 'salary', 'experience'),
  ('', (current_timestamp - interval '275 hour'), 'description', 'location', 11, 'salary', 'experience'),
  ('', (current_timestamp - interval '184 hour'), 'description', 'location', 11, 'salary', 'experience'),
  ('', (current_timestamp - interval '10 hour'), 'description', 'location', 11, 'salary', 'experience'),
  ('', (current_timestamp - interval '140 hour'), 'description', 'location', 12, 'salary', 'experience'),
  ('', (current_timestamp - interval '90 hour'), 'description', 'location', 12, 'salary', 'experience'),
  ('', (current_timestamp - interval '36 hour'), 'description', 'location', 12, 'salary', 'experience')
;