INSERT INTO jobs
  (
  title,
  created_at,
  description,
  location,
  organization_id,
  salary,
  experience
  )
VALUES
  ('Corporate Law Administrative Assistant', (current_timestamp - interval '300 hour'), 'Yuccie pug beard cronut, farm-to-table listicle narwhal wolf whatever tattooed mumblecore sartorial kogi sustainable pok pok. Artisan godard food truck kickstarter, microdosing sriracha bitters you probably havent heard of them. Portland brooklyn freegan, etsy quinoa celiac mustache asymmetrical tattooed wolf. Lyft you probably havent heard of them kombucha chillwave unicorn readymade, chambray cred.', 'Vernon, BC', 1, '$50,000', '3 years to less than 5 years'),
  ('Superintendent, Building ', (current_timestamp - interval '200 hour'), 'helvetica poke meh actually fashion axe whatever. Cold-pressed vexillologist kitsch tacos. Four dollar toast knausgaard helvetica vice iPhone williamsburg truffaut. Truffaut swag ramps scenester, crucifix post-ironic lumbersexual shoreditch food truck air plant tilde mumblecore wolf. Snackwave paleo drinking vinegar kinfolk kale chips listicle. Plaid cray franzen readymade, cold-pressed fingerstache iceland everyday carry banh mi shaman schlitz gluten-free gochujang photo booth. Single-origin coffee gochujang selvage hot chicken literally iceland.', 'Gatineau, QC', 1, 'Salary$$38,000 to $40,000', '1 year to less than 2 years'),
  ('Property Manager', (current_timestamp - interval '100 hour'), 'tofu chicharrones tumblr organic. Shaman +1 church-key sustainable microdosing, butcher 3 wolf moon polaroid asymmetrical snackwave banh mi neutra. Locavore coloring book mustache, chillwave semiotics beard wolf artisan pinterest skateboard everyday carry retro. XOXO vice venmo jean shorts normcore selvage. Tilde semiotics roof party, butcher woke before they sold out hella paleo everyday carry typewriter fanny pack', 'Truro Heights, NS', 1, '$32,000 to $42,000', 'No experience'),
  ('Corporate Law Administrative Assistant ', (current_timestamp - interval '50 hour'), 'Unicorn shabby chic art party schlitz everyday carry PBR&B chia DIY meh flannel direct trade. Truffaut crucifix live-edge banh mi viral iceland, marfa tbh. Twee seitan selvage chicharrones, neutra green juice cray locavore craft beer +1. VHS mustache lumbersexual man braid fingerstache roof party keytar pour-over keffiyeh next level. Quinoa cloud bread photo booth tilde chia, knausgaard cray succulents forage small batch meggings godard everyday carry raclette.', 'Vernon, BC', 1, '$50,000', '3 years to less than 5 years'),
  ('', (current_timestamp - interval '210 hour'), 'description', 'location', 2, 'salary', 'experience'),
  ('Department Manager - Retail', (current_timestamp - interval '30 hour'), 'IPhone next level humblebrag tilde franzen hoodie tacos enamel pin VHS you probably havent heard of them tofu flannel. Lo-fi squid pug iPhone palo santo, art party franzen pop-up slow-carb. 8-bit irony poutine, flexitarian synth godard tbh edison bulb pabst chartreuse readymade. Street art meggings chicharrones celiac jean shorts crucifix kogi vexillologist letterpress portland chillwave ethical. Gluten-free stumptown edison bulb, sustainable cronut raw denim banh mi iPhone bitters photo booth intelligentsia neutra shaman meh next level.', 'Unionville, ON', 2, '$93,500', '2 years to less than 3 years'),
  ('Recruiting Manager', (current_timestamp - interval '400 hour'), 'Paleo cornhole tattooed, lyft edison bulb austin brooklyn. Vegan la croix raw denim mlkshk pok pok keytar snackwave try-hard literally small batch 90s swag meggings cornhole jianbing. Actually kitsch irony, master cleanse schlitz biodiesel craft beer gastropub meh pour-over yr banh mi you probably havent heard of them chia humblebrag. Raw denim bicycle rights quinoa scenester bespoke taxidermy franzen selfies +1 you probably havent heard of them church-key leggings.', 'LocationKentville, NS', 3, '$63,000', '3 years to less than 5 years'),
  ('', (current_timestamp - interval '330 hour'), 'description', 'location', 3, 'salary', 'experience'),
  ('', (current_timestamp - interval '210 hour'), 'description', 'location', 3, 'salary', 'experience'),
  ('', (current_timestamp - interval '180 hour'), 'description', 'location', 3, 'salary', 'experience'),
  ('', (current_timestamp - interval '400 hour'), 'description', 'location', 4, 'salary', 'experience'),
  ('Technical Support Analyst - Systems', (current_timestamp - interval '140 hour'), 'Vape cred wolf banh mi try-hard edison bulb wayfarers freegan. You probably havent heard of them normcore mumblecore master cleanse coloring book. Quinoa cardigan ennui squid. Whatever shoreditch gentrify wolf shabby chic.', 'Saint John, NB', 4, '$35,000 to $38,500', '1 year to less than 2 years'),
  ('', (current_timestamp - interval '10 hour'), 'description', 'location', 4, 'salary', 'experience'),
  ('', (current_timestamp - interval '200 hour'), 'description', 'location', 5, 'salary', 'experience'),
  ('', (current_timestamp - interval '160 hour'), 'description', 'location', 5, 'salary', 'experience'),
  ('Engineering Scientist', (current_timestamp - interval '80 hour'), 'Hexagon marfa williamsburg swag kinfolk ennui squid. Glossier godard cliche, hammock succulents art party street art PBR&B austin iceland actually snackwave. Intelligentsia umami thundercats occupy af enamel pin waistcoat messenger bag williamsburg. Poke literally mustache normcore ethical, etsy sartorial. Glossier DIY raclette, cold-pressed chillwave pitchfork XOXO activated charcoal VHS chicharrones butcher 90s cardigan. Taxidermy small batch master cleanse migas kinfolk gochujang, craft beer kogi austin locavore raw denim kale chips tofu. Master cleanse man bun enamel pin four dollar toast wolf echo park scenester affogato paleo biodiesel truffaut butcher hella.', 'Abbotsford, BC', 5, '$76,000', '7 months to less than 1 year'),
  ('', (current_timestamp - interval '50 hour'), 'description', 'location', 5, 'salary', 'experience'),
  ('', (current_timestamp - interval '90 hour'), 'description', 'location', 6, 'salary', 'experience'),
  ('Fast Food Restaurant Manager', (current_timestamp - interval '20 hour'), 'Celiac mumblecore wayfarers raw denim pitchfork tilde snackwave. Readymade seitan succulents DIY. Occupy williamsburg brunch +1, pug mumblecore af mixtape hoodie pickled chicharrones godard hammock mustache. Thundercats four loko celiac, intelligentsia knausgaard neutra adaptogen chia single-origin coffee. Yuccie cardigan aesthetic ugh. Direct trade schlitz blog chillwave flannel live-edge hot chicken green juice fixie slow-carb. Activated charcoal normcore squid, raw denim lyft trust fund skateboard air plant tumblr butcher pug vaporware cardigan.', 'Salaberry-de-Valleyfield, QC', 6, '$43,000', '1 year to less than 2 years '),
  ('', (current_timestamp - interval '100 hour'), 'description', 'location', 7, 'salary', 'experience'),
  ('', (current_timestamp - interval '50 hour'), 'description', 'location', 7, 'salary', 'experience'),
  ('', (current_timestamp - interval '40 hour'), 'description', 'location', 7, 'salary', 'experience'),
  ('', (current_timestamp - interval '130 hour'), 'description', 'location', 8, 'salary', 'experience'),
  ('', (current_timestamp - interval '90 hour'), 'description', 'location', 8, 'salary', 'experience'),
  ('', (current_timestamp - interval '50 hour'), 'description', 'location', 8, 'salary', 'experience'),
  ('Pilot, Airline', (current_timestamp - interval '34 hour'), 'Organic try-hard squid gochujang keffiyeh. Schlitz selvage craft beer, you probably havent heard of them semiotics offal sustainable single-origin coffee chartreuse bushwick dreamcatcher viral. Selvage tilde man bun williamsburg waistcoat. Aesthetic PBR&B lo-fi mumblecore hell of. Lo-fi meh farm-to-table, messenger bag kinfolk etsy cronut woke vaporware wayfarers. Vinyl chartreuse asymmetrical, flexitarian 3 wolf moon microdosing keytar church-key street art pabst shaman.', 'La Ronge, SK', 8, '$70,440.6 to $84,279.48', '3 years to less than 5 years'),
  ('', (current_timestamp - interval '3 hour'), 'description', 'location', 8, 'salary', 'experience'),
  ('', (current_timestamp - interval '120 hour'), 'description', 'location', 9, 'salary', 'experience'),
  ('', (current_timestamp - interval '84 hour'), 'description', 'location', 9, 'salary', 'experience'),
  ('', (current_timestamp - interval '200 hour'), 'description', 'location', 10, 'salary', 'experience'),
  ('', (current_timestamp - interval '150 hour'), 'description', 'location', 10, 'salary', 'experience'),
  ('', (current_timestamp - interval '20 hour'), 'description', 'location', 10, 'salary', 'experience'),
  ('Insurance Broker', (current_timestamp - interval '310 hour'), 'Fixie occupy intelligentsia iceland, yr prism etsy XOXO freegan pok pok raclette drinking vinegar truffaut +1 tilde. Vape lomo dreamcatcher, 90s disrupt 8-bit copper mug. Knausgaard intelligentsia umami cold-pressed actually sriracha hell of. Knausgaard master cleanse flexitarian drinking vinegar, deep v poutine fam bespoke portland woke jianbing brunch.', 'Various locations', 11, '$36,000 to $46,000', 'No experience'),
  ('', (current_timestamp - interval '275 hour'), 'description', 'location', 11, 'salary', 'experience'),
  ('', (current_timestamp - interval '184 hour'), 'description', 'location', 11, 'salary', 'experience'),
  ('', (current_timestamp - interval '10 hour'), 'description', 'location', 11, 'salary', 'experience'),
  ('', (current_timestamp - interval '140 hour'), 'description', 'location', 12, 'salary', 'experience'),
  ('', (current_timestamp - interval '90 hour'), 'description', 'location', 12, 'salary', 'experience'),
  ('', (current_timestamp - interval '36 hour'), 'description', 'location', 12, 'salary', 'experience')
;