-- INSERT INTO applications
--   (
--   user_id,
--   job_id,
--   message,
--   resume,
--   created_at
--   )
-- VALUES
--   (4, 1, 'Gingerbread cheesecake gummies cheesecake brownie sugar plum macaroon. Biscuit apple pie macaroon shortbread tiramisu cookie. Sweet roll shortbread fruitcake croissant pastry cupcake lollipop. ', 'public/uploads/test.pdf', 'Fri, 14 Jan 2022 23:00:00 GMT'),
--   (2, 1, 'Gingerbread cheesecake gummies cheesecake brownie sugar plum macaroon. Biscuit apple pie macaroon shortbread tiramisu cookie. Sweet roll shortbread fruitcake croissant pastry cupcake lollipop. ', 'public/uploads/test.pdf', 'Fri, 17 Jan 2022 23:00:00 GMT'),
--   (3, 2, 'Gingerbread cheesecake gummies cheesecake brownie sugar plum macaroon. Biscuit apple pie macaroon shortbread tiramisu cookie. Sweet roll shortbread fruitcake croissant pastry cupcake lollipop. ', 'public/uploads/test.pdf', 'Fri, 14 Jan 2022 23:00:00 GMT'),
--   (2, 2, 'Curabitur gravida Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 'public/uploads/test.pdf', 'Fri, 14 Jan 2022 23:00:00 GMT'),
--   (4, 2, 'Curabitur gravida Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 'public/uploads/test.pdf', 'Fri, 23 Jan 2022 23:00:00 GMT')